spring:
  application.name: kafka-triage
  data.web:
    pageable:
      default-page-size: 10
      max-page-size: 100
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    password:
    platform: dev
    separator: ';;'
    url: jdbc:postgresql://192.168.99.100/test
    username: test
  jackson:
    default-property-inclusion: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true
  flyway:
    enabled: false
  profiles.active:

