version: "3.7"
services:
  postgres:
    command: postgres -c 'shared_preload_libraries=pg_stat_statements' -c 'pg_stat_statements.save=off' -c 'pg_stat_statements.max=100'
    environment:
      - "POSTGRES_USER=test"
    image: postgres:9.6-alpine
    init: true
    ports:
      - "5432:5432"
